# SPDX-License-Identifier: GPL-3.0-only

"""Gowin DDR3 controller for the Tang Console 138K x32 array as a LiteDRAM native port.

The controller, its 400 MHz PLL, and the PG484 pin and placement constraints are the
configuration proven by gateware/ddr3_vendor, regenerated by scripts/gen-ddr3-ip.sh.
"""

from pathlib import Path

from migen import Cat, ClockDomain, ClockDomainsRenamer, ClockSignal, Instance, ResetSignal, Signal
from migen.genlib.cdc import MultiReg
from migen.genlib.resetsync import AsyncResetSynchronizer

from litex.gen import LiteXModule
from litex.build.generic_platform import IOStandard, Misc, Pins, Subsignal
from litex.soc.interconnect import stream
from litex.soc.interconnect.csr import AutoCSR, CSRField, CSRStatus

from litedram.common import LiteDRAMNativePort
from litedram.frontend.adapter import LiteDRAMNativePortCDC


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "gateware/ddr3_vendor"

ADDRESS_BITS = 25          # 1 GiB in 256-bit native words.
DATA_WIDTH   = 256
SIZE         = 1 << 30


def ddram32_io():
    """Full x32 DDR3 pin map from Sipeed's TangMega-138K ddr_memory example (Apache-2.0)."""
    sstl = [IOStandard("SSTL15"), Misc("DRIVE=8")]
    diff = [IOStandard("SSTL15D"), Misc("DRIVE=8")]
    return [
        ("ddram32", 0,
            Subsignal("a", Pins(
                "M1 K2 G2 J4 J2 H2 G3 J1",
                "J5 H5 L1 H3 K4 K1 D1"), *sstl),
            Subsignal("ba",      Pins("P5 P2 M6"), *sstl),
            Subsignal("cs_n",    Pins("P4"), *sstl),
            Subsignal("ras_n",   Pins("L5"), *sstl),
            Subsignal("cas_n",   Pins("L4"), *sstl),
            Subsignal("we_n",    Pins("M5"), *sstl),
            Subsignal("cke",     Pins("K6"), *sstl),
            Subsignal("odt",     Pins("M2"), *sstl),
            Subsignal("reset_n", Pins("L6"), *sstl),
            Subsignal("dm",      Pins("AA4 V7 T6 W1"), *sstl),
            Subsignal("dq", Pins(
                " Y4 AB3 AA5  V4 AA1 AB2 AB5 AB1",
                "AA8  Y8 AB7  Y7 AB8  W9 AB6  Y9",
                " U5  R6  U6  R4  Y6  T4  V5  T5",
                " W2  Y1  T1  U3  U2  V2  U1  Y2"), *sstl),
            Subsignal("dqs_p",   Pins("Y3 V9 W6 R3"), *diff),
            Subsignal("dqs_n",   Pins("AA3 V8 W5 R2"), *diff),
            Subsignal("clk_p",   Pins("L3"), *diff),
            Subsignal("clk_n",   Pins("K3"), *diff),
            Misc("PULL_MODE=NONE BANK_VCCIO=1.5"),
        ),
    ]


def add_sources(platform, ip_dir):
    ip_dir = Path(ip_dir)
    sources = [
        ip_dir / "ddr3_memory_interface/ddr3_memory_interface.v",
        ip_dir / "gowin_pll/gowin_pll_mod.v",
        ip_dir / "gowin_pll/pll_init.v",
    ]
    for source in sources:
        if not source.is_file():
            raise FileNotFoundError(f"{source} is missing; run scripts/gen-ddr3-ip.sh {ip_dir}")
        platform.add_source(str(source))
    platform.add_source(str(SOURCE_DIR / "gowin_ddr3_native.sv"))


class GowinDDR3(LiteXModule, AutoCSR):
    """Gowin DDR3 controller exposed as a sys-domain LiteDRAM native port.

    `clk50` is the 50 MHz board clock and `rst` holds the DDR PLL and controller in reset.
    """

    def __init__(self, platform, pads, clk50, rst, ip_dir):
        add_sources(platform, ip_dir)
        platform.toolchain.additional_cst_commands += [
            'INS_LOC "u_ddr_pll_mod/PLL_inst" PLL_L[0];',
            'INS_LOC "u_ddr3/gw3_top/u_ddr_phy_top/u_dll" DDRDLLM_BL;',
            'INS_LOC "u_ddr3/gw3_top/u_ddr_phy_top/fclkdiv" LEFTSIDE[4];',
        ]

        self.cd_ddr = ClockDomain()
        self.port = LiteDRAMNativePort("both", ADDRESS_BITS, DATA_WIDTH, clock_domain="sys")
        ddr_port = LiteDRAMNativePort("both", ADDRESS_BITS, DATA_WIDTH, clock_domain="ddr")

        self.pll_lock   = pll_lock   = Signal()
        self.calib_done = calib_done = Signal()
        self.memory_clk = memory_clk = Signal(name="ddr3_memory_clk")
        pll_stop   = Signal()
        pll_raw    = Signal()
        pll_rst    = Signal()
        icpsel     = Signal(6)
        lpfres     = Signal(3)
        ddr_rst    = Signal()
        overflow   = Signal()

        # 50 MHz -> 800 MHz VCO -> 400 MHz memory clock, with Gowin's loop-filter search.
        self.specials += [
            Instance("Gowin_PLL_MOD", name="u_ddr_pll_mod",
                i_clkin   = clk50,
                i_reset   = pll_rst,
                i_icpsel  = icpsel,
                i_lpfres  = lpfres,
                i_lpfcap  = 0,
                i_enclk0  = 1,
                i_enclk1  = 1,
                i_enclk2  = pll_stop,
                o_clkout2 = memory_clk,
                o_lock    = pll_raw,
            ),
            Instance("PLL_INIT", name="u_ddr_pll_init",
                p_CLK_PERIOD = 20,
                p_MULTI_FAC  = 16,
                i_CLKIN   = clk50,
                i_I_RST   = rst,
                o_O_RST   = pll_rst,
                i_PLLLOCK = pll_raw,
                o_O_LOCK  = pll_lock,
                o_ICPSEL  = icpsel,
                o_LPFRES  = lpfres,
            ),
        ]

        # Controller command/data signals in the ddr domain.
        ctrl = {name: Signal(width, name=f"ddr3_{name}") for name, width in [
            ("cmd_ready", 1), ("cmd", 3), ("cmd_en", 1), ("addr", 29),
            ("wr_data_rdy", 1), ("wr_data", 256), ("wr_data_en", 1), ("wr_data_end", 1),
            ("wr_data_mask", 32), ("rd_data", 256), ("rd_data_valid", 1),
        ]}

        self.specials += Instance("DDR3_Memory_Interface_Top", name="u_ddr3",
            i_clk                 = clk50,
            i_memory_clk          = memory_clk,
            i_pll_lock            = pll_lock,
            o_pll_stop            = pll_stop,
            i_rst_n               = ~rst,
            o_clk_out             = self.cd_ddr.clk,
            o_ddr_rst             = ddr_rst,
            o_init_calib_complete = calib_done,
            o_cmd_ready           = ctrl["cmd_ready"],
            i_cmd                 = ctrl["cmd"],
            i_cmd_en              = ctrl["cmd_en"],
            i_addr                = ctrl["addr"],
            o_wr_data_rdy         = ctrl["wr_data_rdy"],
            i_wr_data             = ctrl["wr_data"],
            i_wr_data_en          = ctrl["wr_data_en"],
            i_wr_data_end         = ctrl["wr_data_end"],
            i_wr_data_mask        = ctrl["wr_data_mask"],
            o_rd_data             = ctrl["rd_data"],
            o_rd_data_valid       = ctrl["rd_data_valid"],
            o_rd_data_end         = Signal(),
            i_sr_req              = 0,
            i_ref_req             = 0,
            o_sr_ack              = Signal(),
            o_ref_ack             = Signal(),
            i_burst               = 0,
            o_O_ddr_addr          = pads.a,
            o_O_ddr_ba            = pads.ba,
            o_O_ddr_cs_n          = pads.cs_n,
            o_O_ddr_ras_n         = pads.ras_n,
            o_O_ddr_cas_n         = pads.cas_n,
            o_O_ddr_we_n          = pads.we_n,
            o_O_ddr_clk           = pads.clk_p,
            o_O_ddr_clk_n         = pads.clk_n,
            o_O_ddr_cke           = pads.cke,
            o_O_ddr_odt           = pads.odt,
            o_O_ddr_reset_n       = pads.reset_n,
            o_O_ddr_dqm           = pads.dm,
            io_IO_ddr_dq          = pads.dq,
            io_IO_ddr_dqs         = pads.dqs_p,
            io_IO_ddr_dqs_n       = pads.dqs_n,
        )
        # The native port stays in reset until calibration completes.
        self.specials += AsyncResetSynchronizer(self.cd_ddr, ddr_rst | ~calib_done)

        # A registered write-data stage keeps the crossing FIFO's flags out of the path from
        # write data to the controller's command enable.
        self.wdata_pipe = wdata_pipe = ClockDomainsRenamer("ddr")(
            stream.PipeValid(ddr_port.wdata.description))
        self.comb += ddr_port.wdata.connect(wdata_pipe.sink)

        # Controller read latency in DDR clocks (gowin_ddr3_native.sv), ddr domain.
        self.latency_count = Signal(32)
        self.latency_sum = Signal(32)
        self.latency_max = Signal(32)
        self.specials += Instance("gowin_ddr3_native",
            p_ADDR_BITS  = ADDRESS_BITS,
            p_READ_DEPTH = 8,
            i_clk                = ClockSignal("ddr"),
            i_rst                = ResetSignal("ddr"),
            i_cmd_valid          = ddr_port.cmd.valid,
            o_cmd_ready          = ddr_port.cmd.ready,
            i_cmd_we             = ddr_port.cmd.we,
            i_cmd_addr           = ddr_port.cmd.addr,
            i_wdata_valid        = wdata_pipe.source.valid,
            o_wdata_ready        = wdata_pipe.source.ready,
            i_wdata_data         = wdata_pipe.source.data,
            i_wdata_we           = wdata_pipe.source.we,
            o_rdata_valid        = ddr_port.rdata.valid,
            i_rdata_ready        = ddr_port.rdata.ready,
            o_rdata_data         = ddr_port.rdata.data,
            i_ctrl_cmd_ready     = ctrl["cmd_ready"],
            o_ctrl_cmd           = ctrl["cmd"],
            o_ctrl_cmd_en        = ctrl["cmd_en"],
            o_ctrl_addr          = ctrl["addr"],
            i_ctrl_wr_data_rdy   = ctrl["wr_data_rdy"],
            o_ctrl_wr_data       = ctrl["wr_data"],
            o_ctrl_wr_data_en    = ctrl["wr_data_en"],
            o_ctrl_wr_data_end   = ctrl["wr_data_end"],
            o_ctrl_wr_data_mask  = ctrl["wr_data_mask"],
            i_ctrl_rd_data       = ctrl["rd_data"],
            i_ctrl_rd_data_valid = ctrl["rd_data_valid"],
            o_reads              = Signal(32),
            o_writes             = Signal(32),
            o_overflow           = overflow,
            o_latency_count      = self.latency_count,
            o_latency_sum        = self.latency_sum,
            o_latency_max        = self.latency_max,
        )

        # A registered read-data stage keeps the crossing FIFO's gray-code
        # compare out of the path to the AE350 AHB read data, and its skid
        # register keeps the clients' rdata ready out of the FIFO's read
        # pointer and block-RAM read address.
        cdc_port = LiteDRAMNativePort("both", ADDRESS_BITS, DATA_WIDTH, clock_domain="sys")
        self.cdc = LiteDRAMNativePortCDC(cdc_port, ddr_port)
        self.rdata_pipe = rdata_pipe = stream.Buffer(cdc_port.rdata.description,
            pipe_valid=True, pipe_ready=True)
        # Likewise a registered write-data stage keeps the crossing FIFO's
        # gray-code full flag out of every client's write-data ready path,
        # which runs through both arbiters into the fabric rasterizer.
        self.wdata_sys_pipe = wdata_sys_pipe = stream.Buffer(
            cdc_port.wdata.description, pipe_valid=True, pipe_ready=True)
        self.comb += [
            self.port.cmd.connect(cdc_port.cmd),
            self.port.wdata.connect(wdata_sys_pipe.sink),
            wdata_sys_pipe.source.connect(cdc_port.wdata),
            cdc_port.rdata.connect(rdata_pipe.sink),
            rdata_pipe.source.connect(self.port.rdata),
        ]

        # Status for firmware and the diagnostic register file.
        self.status_sys = Signal(3)
        self.specials += MultiReg(Cat(calib_done, pll_lock, overflow), self.status_sys, "sys")
        self._status = CSRStatus(fields=[
            CSRField("calib_done", size=1, description="Controller calibration complete"),
            CSRField("pll_lock",   size=1, description="400 MHz memory PLL locked"),
            CSRField("overflow",   size=1, description="Read-return FIFO overflow (must stay 0)"),
        ])
        # A CSRStatus with fields drives its status word from the field signals.
        self.comb += [
            self._status.fields.calib_done.eq(self.status_sys[0]),
            self._status.fields.pll_lock.eq(self.status_sys[1]),
            self._status.fields.overflow.eq(self.status_sys[2]),
        ]

        # Clock constraints follow the reference design's exclusive clock groups.
        platform.add_period_constraint(memory_clk, 2.5)
        platform.add_period_constraint(self.cd_ddr.clk, 10.0)
